# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Magdalena Piwko's Personal Blog
email: barry@barrymister.com
description: >
  Welcome to Magdalena Piwko’s personal blog! Magdalena is a devoted mother, 
  loving wife, and hardworking Polish woman. This blog is her space to share 
  her thoughts, passions, and experiences with the world. Here, she will write 
  about the things that inspire her, the topics she loves, and the stories she 
  wants to share with others who have similar interests.

  Whether it’s about family, life, culture, or her unique perspectives, this blog 
  is a warm and welcoming place for anyone who wants to connect and engage. 
  Join her on this journey as she expresses her ideas, shares meaningful moments, 
  and creates a space for conversation, inspiration, and connection.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://magdalenapiwko.com/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
